// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using muchik.market.pay.infraestructure.context;

#nullable disable

namespace muchik.market.pay.infraestructure.Migrations
{
    [DbContext(typeof(PaymentContext))]
    partial class PaymentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("muchik.market.pay.domain.entities.Payment", b =>
                {
                    b.Property<int>("Id_Operation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_operation");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<int>("Id_Invoice")
                        .HasColumnType("int")
                        .HasColumnName("id_invoice");

                    b.HasKey("Id_Operation");

                    b.ToTable("payment", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
